# This workflow installs saltcorn from npm and runs the plugin tests.

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saltcorn_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - run: npm install -g @saltcorn/cli@next
        env:
          CI: true
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
      - run: saltcorn info
        env:
          CI: true
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
      - run: saltcorn add-schema -f
        env:
          CI: true
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
      - run: saltcorn dev:plugin-test -d $PWD -f backup.zip
        env:
          CI: true
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
