# This workflow installs saltcorn from GitHub and runs the plugin tests

# There seems to be a problem when saltcorn is installed from npm and jest runs in the node_modules directory
# when we update jest to:
# https://github.com/jestjs/jest/issues/11781#issuecomment-1050262337
# we can try again with
# https://github.com/jestjs/jest/pull/11084

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saltcorn_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: cd ../ && git clone https://github.com/saltcorn/saltcorn
      - run: cd ../saltcorn && npm install --legacy-peer-deps && npm run tsc
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          SKIP_DOCKER_IMAGE_INSTALL: "true"
      - run: cd ../saltcorn && packages/saltcorn-cli/bin/saltcorn add-schema -f
        env:
          CI: true
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
      - run: ../saltcorn/packages/saltcorn-cli/bin/saltcorn dev:plugin-test -d $PWD -f backup.zip
        env:
          CI: true
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
